
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using System;
using Cybtans.Serialization;

namespace Cybtans.Tests.Models
{
	public class CustomerProfileDto : IReflectorMetadataProvider
	{
		private static readonly CustomerProfileDtoAccesor __accesor = new CustomerProfileDtoAccesor();
		
		public string Name {get; set;}
		
		public Guid Id {get; set;}
		
		public DateTime? CreateDate {get; set;}
		
		public DateTime? UpdateDate {get; set;}
		
		public IReflectorMetadata GetAccesor()
		{
			return __accesor;
		}
	
		#region CustomerProfileDto  Accesor
		public sealed class CustomerProfileDtoAccesor : IReflectorMetadata
		{
			public const int Name = 1;
			public const int Id = 2;
			public const int CreateDate = 3;
			public const int UpdateDate = 4;
			private readonly int[] _props = new int[]
			{
				Name,Id,CreateDate,UpdateDate
			};
			
			public int[] GetPropertyCodes() => _props;
			
			public string GetPropertyName(int propertyCode)
			{
			    return propertyCode switch
			    {
			       Name => "Name",
			       Id => "Id",
			       CreateDate => "CreateDate",
			       UpdateDate => "UpdateDate",
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			
			public int GetPropertyCode(string propertyName)
			{
			    return propertyName switch
			    {
			        "Name" => Name,
			        "Id" => Id,
			        "CreateDate" => CreateDate,
			        "UpdateDate" => UpdateDate,
			
			        _ => -1,
			    };
			}
			
			public Type GetPropertyType(int propertyCode)
			{
			    return propertyCode switch
			    {
			        Name => typeof(string),
			        Id => typeof(Guid),
			        CreateDate => typeof(DateTime?),
			        UpdateDate => typeof(DateTime?),
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			       
			public object GetValue(object target, int propertyCode)
			{
			    CustomerProfileDto obj = (CustomerProfileDto)target;
			    return propertyCode switch
			    {
			        Name => obj.Name,
			        Id => obj.Id,
			        CreateDate => obj.CreateDate,
			        UpdateDate => obj.UpdateDate,
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			
			public void SetValue(object target, int propertyCode, object value)
			{
			    CustomerProfileDto obj = (CustomerProfileDto)target;
			    switch (propertyCode)
			    {
			        case Name:  obj.Name = (string)value;break;
			        case Id:  obj.Id = (Guid)value;break;
			        case CreateDate:  obj.CreateDate = (DateTime?)value;break;
			        case UpdateDate:  obj.UpdateDate = (DateTime?)value;break;
			
			        default: throw new InvalidOperationException("property code not supported");
			    }
			}
		
		}
		#endregion
	
	
	}

}
