
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using System;
using Cybtans.Serialization;

namespace Cybtans.Tests.Models
{
	public class GetOrderNameRequest : IReflectorMetadataProvider
	{
		private static readonly GetOrderNameRequestAccesor __accesor = new GetOrderNameRequestAccesor();
		
		public string Id {get; set;}
		
		public IReflectorMetadata GetAccesor()
		{
			return __accesor;
		}
		public static implicit operator GetOrderNameRequest(string id)
		{
			return new GetOrderNameRequest { Id = id };
		}
	
	
		#region GetOrderNameRequest  Accesor
		public sealed class GetOrderNameRequestAccesor : IReflectorMetadata
		{
			public const int Id = 1;
			private readonly int[] _props = new []
			{
				Id
			};
			
			public int[] GetPropertyCodes() => _props;
			
			public string GetPropertyName(int propertyCode)
			{
			    return propertyCode switch
			    {
			       Id => "Id",
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			
			public int GetPropertyCode(string propertyName)
			{
			    return propertyName switch
			    {
			        "Id" => Id,
			
			        _ => -1,
			    };
			}
			
			public Type GetPropertyType(int propertyCode)
			{
			    return propertyCode switch
			    {
			        Id => typeof(string),
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			       
			public object GetValue(object target, int propertyCode)
			{
			    GetOrderNameRequest obj = (GetOrderNameRequest)target;
			    return propertyCode switch
			    {
			        Id => obj.Id,
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			
			public void SetValue(object target, int propertyCode, object value)
			{
			    GetOrderNameRequest obj = (GetOrderNameRequest)target;
			    switch (propertyCode)
			    {
			        case Id:  obj.Id = (string)value;break;
			
			        default: throw new InvalidOperationException("property code not supported");
			    }
			}
		
		}
		#endregion
	
	
	}

}
