
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using System;
using Cybtans.Serialization;

namespace Cybtans.Tests.Models
{
	public class OrderNamesDto : IReflectorMetadataProvider
	{
		private static readonly OrderNamesDtoAccesor __accesor = new OrderNamesDtoAccesor();
		
		public string Id {get; set;}
		
		public string Description {get; set;}
		
		public IReflectorMetadata GetAccesor()
		{
			return __accesor;
		}
	
		#region OrderNamesDto  Accesor
		public sealed class OrderNamesDtoAccesor : IReflectorMetadata
		{
			public const int Id = 1;
			public const int Description = 2;
			private readonly int[] _props = new int[]
			{
				Id,Description
			};
			
			public int[] GetPropertyCodes() => _props;
			
			public string GetPropertyName(int propertyCode)
			{
			    return propertyCode switch
			    {
			       Id => "Id",
			       Description => "Description",
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			
			public int GetPropertyCode(string propertyName)
			{
			    return propertyName switch
			    {
			        "Id" => Id,
			        "Description" => Description,
			
			        _ => -1,
			    };
			}
			
			public Type GetPropertyType(int propertyCode)
			{
			    return propertyCode switch
			    {
			        Id => typeof(string),
			        Description => typeof(string),
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			       
			public object GetValue(object target, int propertyCode)
			{
			    OrderNamesDto obj = (OrderNamesDto)target;
			    return propertyCode switch
			    {
			        Id => obj.Id,
			        Description => obj.Description,
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			
			public void SetValue(object target, int propertyCode, object value)
			{
			    OrderNamesDto obj = (OrderNamesDto)target;
			    switch (propertyCode)
			    {
			        case Id:  obj.Id = (string)value;break;
			        case Description:  obj.Description = (string)value;break;
			
			        default: throw new InvalidOperationException("property code not supported");
			    }
			}
		
		}
		#endregion
	
	
	}

}
