
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using System;
using Cybtans.Serialization;

namespace Cybtans.Tests.Models
{
	public class UploadImageResponse : IReflectorMetadataProvider
	{
		private static readonly UploadImageResponseAccesor __accesor = new UploadImageResponseAccesor();
		
		public string Url {get; set;}
		
		public string M5Checksum {get; set;}
		
		public IReflectorMetadata GetAccesor()
		{
			return __accesor;
		}
	
		#region UploadImageResponse  Accesor
		public sealed class UploadImageResponseAccesor : IReflectorMetadata
		{
			public const int Url = 1;
			public const int M5Checksum = 2;
			private readonly int[] _props = new int[]
			{
				Url,M5Checksum
			};
			
			public int[] GetPropertyCodes() => _props;
			
			public string GetPropertyName(int propertyCode)
			{
			    return propertyCode switch
			    {
			       Url => "Url",
			       M5Checksum => "M5Checksum",
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			
			public int GetPropertyCode(string propertyName)
			{
			    return propertyName switch
			    {
			        "Url" => Url,
			        "M5Checksum" => M5Checksum,
			
			        _ => -1,
			    };
			}
			
			public Type GetPropertyType(int propertyCode)
			{
			    return propertyCode switch
			    {
			        Url => typeof(string),
			        M5Checksum => typeof(string),
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			       
			public object GetValue(object target, int propertyCode)
			{
			    UploadImageResponse obj = (UploadImageResponse)target;
			    return propertyCode switch
			    {
			        Url => obj.Url,
			        M5Checksum => obj.M5Checksum,
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			
			public void SetValue(object target, int propertyCode, object value)
			{
			    UploadImageResponse obj = (UploadImageResponse)target;
			    switch (propertyCode)
			    {
			        case Url:  obj.Url = (string)value;break;
			        case M5Checksum:  obj.M5Checksum = (string)value;break;
			
			        default: throw new InvalidOperationException("property code not supported");
			    }
			}
		
		}
		#endregion
	
	
	}

}
