
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using System;
using Cybtans.Serialization;

namespace Cybtans.Tests.Models
{
	public class UploadStreamResponse : IReflectorMetadataProvider
	{
		private static readonly UploadStreamResponseAccesor __accesor = new UploadStreamResponseAccesor();
		
		public string M5Checksum {get; set;}
		
		public IReflectorMetadata GetAccesor()
		{
			return __accesor;
		}
		public static implicit operator UploadStreamResponse(string m5Checksum)
		{
			return new UploadStreamResponse { M5Checksum = m5Checksum };
		}
	
	
		#region UploadStreamResponse  Accesor
		public sealed class UploadStreamResponseAccesor : IReflectorMetadata
		{
			public const int M5Checksum = 1;
			private readonly int[] _props = new int[]
			{
				M5Checksum
			};
			
			public int[] GetPropertyCodes() => _props;
			
			public string GetPropertyName(int propertyCode)
			{
			    return propertyCode switch
			    {
			       M5Checksum => "M5Checksum",
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			
			public int GetPropertyCode(string propertyName)
			{
			    return propertyName switch
			    {
			        "M5Checksum" => M5Checksum,
			
			        _ => -1,
			    };
			}
			
			public Type GetPropertyType(int propertyCode)
			{
			    return propertyCode switch
			    {
			        M5Checksum => typeof(string),
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			       
			public object GetValue(object target, int propertyCode)
			{
			    UploadStreamResponse obj = (UploadStreamResponse)target;
			    return propertyCode switch
			    {
			        M5Checksum => obj.M5Checksum,
			
			        _ => throw new InvalidOperationException("property code not supported"),
			    };
			}
			
			public void SetValue(object target, int propertyCode, object value)
			{
			    UploadStreamResponse obj = (UploadStreamResponse)target;
			    switch (propertyCode)
			    {
			        case M5Checksum:  obj.M5Checksum = (string)value;break;
			
			        default: throw new InvalidOperationException("property code not supported");
			    }
			}
		
		}
		#endregion
	
	
	}

}
