
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using Cybtans.Tests.Clients;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using mds = global::Cybtans.Tests.Models;

namespace Cybtans.Tests.Controllers
{
	/// <summary>
	/// Jwt Authentication Service
	/// </summary>
	[System.ComponentModel.Description("Jwt Authentication Service")]
	[Route("api/auth")]
	[ApiController]
	public partial class AuthenticationServiceController : ControllerBase
	{
		private readonly IAuthenticationServiceClient _service;
		
		public AuthenticationServiceController(IAuthenticationServiceClient service)
		{
			_service = service;
		}
		
		/// <summary>
		/// Generates an access token
		/// </summary>
		[System.ComponentModel.Description("Generates an access token")]
		[HttpPost("login")]
		public Task<mds::LoginResponse> Login([FromBody]mds::LoginRequest request)
		{
			return _service.Login(request);
		}
	}

}
