
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using Cybtans.Tests.Clients;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using mds = global::Cybtans.Tests.Models;

namespace Cybtans.Tests.Controllers
{
	[Route("api/CustomerEvent")]
	[ApiController]
	public partial class CustomerEventServiceController : ControllerBase
	{
		private readonly ICustomerEventServiceClient _service;
		
		public CustomerEventServiceController(ICustomerEventServiceClient service)
		{
			_service = service;
		}
		
		[HttpGet]
		public Task<mds::GetAllCustomerEventResponse> GetAll([FromQuery]mds::GetAllRequest request)
		{
			return _service.GetAll(request);
		}
		
		[HttpGet("{id}")]
		public Task<mds::CustomerEventDto> Get(Guid id, [FromQuery]mds::GetCustomerEventRequest request)
		{
			request.Id = id;
			return _service.Get(request);
		}
		
		[HttpPost]
		public Task<mds::CustomerEventDto> Create([FromBody]mds::CreateCustomerEventRequest request)
		{
			return _service.Create(request);
		}
		
		[HttpPut("{id}")]
		public Task<mds::CustomerEventDto> Update(Guid id, [FromBody]mds::UpdateCustomerEventRequest request)
		{
			request.Id = id;
			return _service.Update(request);
		}
		
		[HttpDelete("{id}")]
		public Task Delete(Guid id, [FromQuery]mds::DeleteCustomerEventRequest request)
		{
			request.Id = id;
			return _service.Delete(request);
		}
	}

}
