
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using Cybtans.Tests.Clients;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using mds = global::Cybtans.Tests.Models;

namespace Cybtans.Tests.Controllers
{
	[Route("api/Customer")]
	[ApiController]
	public partial class CustomerServiceController : ControllerBase
	{
		private readonly ICustomerServiceClient _service;
		
		public CustomerServiceController(ICustomerServiceClient service)
		{
			_service = service;
		}
		
		[HttpGet]
		public Task<mds::GetAllCustomerResponse> GetAll([FromQuery]mds::GetAllRequest request)
		{
			return _service.GetAll(request);
		}
		
		[HttpGet("{id}")]
		public Task<mds::CustomerDto> Get(Guid id, [FromQuery]mds::GetCustomerRequest request)
		{
			request.Id = id;
			return _service.Get(request);
		}
		
		[HttpPost]
		public Task<mds::CustomerDto> Create([FromBody]mds::CreateCustomerRequest request)
		{
			return _service.Create(request);
		}
		
		[HttpPut("{id}")]
		public Task<mds::CustomerDto> Update(Guid id, [FromBody]mds::UpdateCustomerRequest request)
		{
			request.Id = id;
			return _service.Update(request);
		}
		
		[HttpDelete("{id}")]
		public Task Delete(Guid id, [FromQuery]mds::DeleteCustomerRequest request)
		{
			request.Id = id;
			return _service.Delete(request);
		}
	}

}
