
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   For support write to ansel@cybtans.com    
// </auto-generated>
//******************************************************

using System;
using Cybtans.Tests.Clients;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using mds = global::Cybtans.Tests.Models;
using Microsoft.AspNetCore.Authorization;

namespace Cybtans.Tests.Controllers
{
	[Route("api/OrderState")]
	[ApiController]
	public partial class OrderStateServiceController : ControllerBase
	{
		private readonly IOrderStateServiceClient _service;
		
		public OrderStateServiceController(IOrderStateServiceClient service)
		{
			_service = service;
		}
		
		[Authorize(Roles = "admin")]
		[HttpGet]
		public Task<mds::GetAllOrderStateResponse> GetAll([FromQuery]mds::GetAllRequest __request)
		{
			return _service.GetAll(__request);
		}
		
		[Authorize(Roles = "admin")]
		[HttpGet("{id}")]
		public Task<mds::OrderStateDto> Get(int id, [FromQuery]mds::GetOrderStateRequest __request)
		{
			__request.Id = id;
			return _service.Get(__request);
		}
		
		[Authorize(Roles = "admin")]
		[HttpPost]
		public Task<mds::OrderStateDto> Create([FromBody]mds::CreateOrderStateRequest __request)
		{
			return _service.Create(__request);
		}
		
		[Authorize(Roles = "admin")]
		[HttpPut("{id}")]
		public Task<mds::OrderStateDto> Update(int id, [FromBody]mds::UpdateOrderStateRequest __request)
		{
			__request.Id = id;
			return _service.Update(__request);
		}
		
		[Authorize(Roles = "admin")]
		[HttpDelete("{id}")]
		public Task Delete(int id, [FromQuery]mds::DeleteOrderStateRequest __request)
		{
			__request.Id = id;
			return _service.Delete(__request);
		}
	}

}
