
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using System.Threading.Tasks;

using models = global::Cybtans.Tests.Models;

namespace Cybtans.Tests.Services
{
	public interface ICustomerEventService 
	{
		
		/// <summary>
		/// Returns a collection of CustomerEventDto
		/// </summary>
		Task<models::GetAllCustomerEventResponse> GetAll(models::GetAllRequest request);
		
		
		/// <summary>
		/// Returns one CustomerEventDto by Id
		/// </summary>
		Task<models::CustomerEventDto> Get(models::GetCustomerEventRequest request);
		
		
		/// <summary>
		/// Creates one CustomerEventDto
		/// </summary>
		Task<models::CustomerEventDto> Create(models::CreateCustomerEventRequest request);
		
		
		/// <summary>
		/// Updates one CustomerEventDto by Id
		/// </summary>
		Task<models::CustomerEventDto> Update(models::UpdateCustomerEventRequest request);
		
		
		/// <summary>
		/// Deletes one CustomerEventDto by Id
		/// </summary>
		Task Delete(models::DeleteCustomerEventRequest request);
		
	}

}
