
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using System.Threading.Tasks;

using models = global::Cybtans.Tests.Models;

namespace Cybtans.Tests.Services
{
	public interface IReadOnlyEntityService 
	{
		
		/// <summary>
		/// Returns a collection of ReadOnlyEntityDto
		/// </summary>
		Task<models::GetAllReadOnlyEntityResponse> GetAll(models::GetAllRequest request);
		
		
		/// <summary>
		/// Returns one ReadOnlyEntityDto by Id
		/// </summary>
		Task<models::ReadOnlyEntityDto> Get(models::GetReadOnlyEntityRequest request);
		
	}

}
