
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using System.Threading.Tasks;

using models = global::Cybtans.Tests.Models;

namespace Cybtans.Tests.Services
{
	public interface ISoftDeleteOrderService 
	{
		
		/// <summary>
		/// Returns a collection of SoftDeleteOrderDto
		/// </summary>
		Task<models::GetAllSoftDeleteOrderResponse> GetAll(models::GetAllRequest request);
		
		
		/// <summary>
		/// Returns one SoftDeleteOrderDto by Id
		/// </summary>
		Task<models::SoftDeleteOrderDto> Get(models::GetSoftDeleteOrderRequest request);
		
		
		/// <summary>
		/// Creates one SoftDeleteOrderDto
		/// </summary>
		Task<models::SoftDeleteOrderDto> Create(models::CreateSoftDeleteOrderRequest request);
		
		
		/// <summary>
		/// Updates one SoftDeleteOrderDto by Id
		/// </summary>
		Task<models::SoftDeleteOrderDto> Update(models::UpdateSoftDeleteOrderRequest request);
		
		
		/// <summary>
		/// Deletes one SoftDeleteOrderDto by Id
		/// </summary>
		Task Delete(models::DeleteSoftDeleteOrderRequest request);
		
	}

}
