
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using System;
using Cybtans.Test.Gateway.Repository.Definition;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using mds = global::Cybtans.Tests.Gateway.Models;

namespace Cybtans.Tests.Grpc.Controllers
{
	[Route("greeter")]
	[ApiController]
	public partial class GreeterController : ControllerBase
	{
		private readonly IGreeter _service;
		
		public GreeterController(IGreeter service)
		{
			_service = service;
		}
		
		[HttpGet("hello")]
		public Task<mds::HelloReply> SayHello([FromQuery]mds::HelloRequest __request)
		{
			return _service.SayHello(__request);
		}
	}

}
