# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(majorMinorPathVersion).$(buildVersion)

# pipeline variables
variables:
   majorMinorPathVersion: 1.0.16
  # semanticVersion counter is automatically incremented by one in each execution of pipeline
  # second parameter is seed value to reset to every time the referenced majorMinorPathVersion is changed
   buildVersion: $[counter(variables['majorMinorPathVersion'], 1)]   

trigger:
  batch: true
  branches:  
    include:
    - master        
  paths:
    include:
      - CybtansSDK/Tools/*

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  displayName: "Publish Code Generator"
  condition: ne(variables['Build.Reason'], 'PullRequest') 
  inputs:
    script: 'dotnet publish CybtansSDK/Tools/Cybtans.Proto.Generator/Cybtans.Proto.Generator.csproj -p:PublishProfile=FolderProfile -o Release'    

- task: ArchiveFiles@2
  displayName: "Zip File"
  condition: ne(variables['Build.Reason'], 'PullRequest') 
  inputs:
    rootFolderOrFile: 'Release/cybtans-cli.exe'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/cybtans-cli-x64.zip'
    replaceExistingArchive: true
    verbose: true

- task: PublishBuildArtifacts@1
  condition: ne(variables['Build.Reason'], 'PullRequest') 
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/cybtans-cli-x64.zip'
    ArtifactName: 'cybtans-cli'
    publishLocation: 'Container'

- task: AzureFileCopy@4
  displayName: 'Upload to Blob Storage'
  condition: ne(variables['Build.Reason'], 'PullRequest') 
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/cybtans-cli-x64.zip'
    azureSubscription: 'Evaluación gratuita(e5d99fb9-0a00-4157-8a2f-e79ac9337a57)'
    Destination: 'AzureBlob'
    storage: 'cybtans'
    ContainerName: 'cybtanssdk'