# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(majorMinorVersion).$(buildVersion)

# pipeline variables
variables:   
   buildVersion: $[counter(variables['majorMinorVersion'], 1)]
   packVersion: $(majorMinorVersion).$(buildVersion)-beta


trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore Cybtans SDK'
  inputs:
    command: 'restore'
    projects: '**/CybtansSDK.sln'   

- task: DotNetCoreCLI@2
  displayName: 'Build Cybtans SDK'
  inputs:
    command: 'build'
    projects: '**/CybtansSDK.sln'
    arguments: '--configuration $(configuration)'
    versioningScheme: 'byBuildNumber' 

- task: CmdLine@2
  displayName: 'Package Nuget Packages'
  inputs:
    script: 'dotnet pack ./**/*.csproj --no-restore --no-build -c $(configuration) -o $(Build.ArtifactStagingDirectory) -p:PackageVersion=$(packVersion) -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/Cybtans*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Cybtans Nuget'
    arguments: '--skip-duplicate'