
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************


export interface HelloModelModel {
  id?: string|null;
  message?: string|null;
}


export interface HelloRequest {
  name?: string|null;
  observations?: string|null;
  date?: string|Date|null;
  data?: string|null;
  nullableInt?: number|undefined|null;
  time?: string|Date|null;
}


export interface HelloReply {
  message?: string|null;
  keywords?: string[]|null;
  info?: HellowInfo|null;
  infoarray?: HellowInfo[]|null;
  date?: string|Date|null;
  time?: string|Date|null;
  observations?: string|null;
  nullableInt?: number|undefined|null;
  data?: string|null;
  helloModel?: HelloModelModel|null;
}


export interface HellowInfo {
  id: number;
  name?: string|null;
  type: HellowInfo_Types_TypeInfo;
  innerA?: HellowInfo_Types_InnerA|null;
}

export interface HellowInfo_Types_InnerA {
  b?: HellowInfo_Types_InnerA_Types_InnerB|null;
}

export interface HellowInfo_Types_InnerA_Types_InnerB {
  type: HellowInfo_Types_InnerA_Types_InnerB_Types_TypeB;
}


export enum HellowInfo_Types_InnerA_Types_InnerB_Types_TypeB {
  a = 0,
  b = 1,
}



export enum HellowInfo_Types_TypeInfo {
  a = 0,
  b = 1,
}

