
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using System;
using System.Collections.Generic;
using System.Linq;

namespace Cybtans.Tests.Grpc.Mappings
{
	public static class GrpcMappingExtensions
	{
		public static global::Cybtans.Tests.Grpc.HelloModelModel ToProtobufModel(this global::Cybtans.Tests.Grpc.Models.HelloModel model)
		{
			if(model == null) return null;
			
			global::Cybtans.Tests.Grpc.HelloModelModel result = new global::Cybtans.Tests.Grpc.HelloModelModel();
			result.Id = model.Id.ToString();
			result.Message = model.Message ?? string.Empty;
			return result;
		}
		
		public static Cybtans.Tests.Grpc.Models.HelloModel ToPocoModel(this global::Cybtans.Tests.Grpc.HelloModelModel model)
		{
			if(model == null) return null;
			
			global::Cybtans.Tests.Grpc.Models.HelloModel result = new global::Cybtans.Tests.Grpc.Models.HelloModel();
			result.Id = !string.IsNullOrEmpty(model.Id) ? Guid.Parse(model.Id) : Guid.Empty;
			result.Message = model.Message;
			return result;
		}
		
	}

}
