
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using Refit;
using Cybtans.Refit;
using System.Net.Http;
using System.Threading.Tasks;
using Cybtans.Tests.Models;

namespace Cybtans.Tests.Clients
{
	[ApiClient]
	public interface IClientServiceClient
	{
		
		[Headers("Authorization: Bearer")]
		[Get("/api/clients/{request.Id}")]
		Task<ClientDto> GetClient(ClientRequest request);
		
		[Headers("Authorization: Bearer")]
		[Get("/api/clients/client2/{request.Id}")]
		Task<ClientDto> GetClient2(ClientRequest request);
		
		[Headers("Authorization: Bearer")]
		[Get("/api/clients/client3/{request.Id}")]
		Task<ClientDto> GetClient3(ClientRequest request);
	
	}

}
