
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using System.Threading.Tasks;
using mds = global::Cybtans.Tests.Models;

namespace Cybtans.Tests.Clients
{
	public interface IClientServiceClient
	{
		
		Task<mds::ClientDto> GetClient(mds::ClientRequest request);
		
		Task<mds::ClientDto> GetClient2(mds::ClientRequest request);
		
		Task<mds::ClientDto> GetClient3(mds::ClientRequest request);
	
	}

}
