
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using System.Threading.Tasks;
using mds = global::Cybtans.Tests.Models;

namespace Cybtans.Tests.Clients
{
	public interface ICustomerEventServiceClient
	{
		
		/// <summary>
		/// Returns a collection of CustomerEventDto
		/// </summary>
		Task<mds::GetAllCustomerEventResponse> GetAll(mds::GetAllRequest request = null);
		
		/// <summary>
		/// Returns one CustomerEventDto by Id
		/// </summary>
		Task<mds::CustomerEventDto> Get(mds::GetCustomerEventRequest request);
		
		/// <summary>
		/// Creates one CustomerEventDto
		/// </summary>
		Task<mds::CustomerEventDto> Create(mds::CreateCustomerEventRequest request);
		
		/// <summary>
		/// Updates one CustomerEventDto by Id
		/// </summary>
		Task<mds::CustomerEventDto> Update(mds::UpdateCustomerEventRequest request);
		
		/// <summary>
		/// Deletes one CustomerEventDto by Id
		/// </summary>
		Task Delete(mds::DeleteCustomerEventRequest request);
	
	}

}
