
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using Refit;
using Cybtans.Refit;
using System.Net.Http;
using System.Threading.Tasks;
using Cybtans.Tests.Models;

namespace Cybtans.Tests.Clients
{
	[ApiClient]
	public interface ICustomerEventServiceClient
	{
		
		/// <summary>
		/// Returns a collection of CustomerEventDto
		/// </summary>
		[Get("/api/CustomerEvent")]
		Task<GetAllCustomerEventResponse> GetAll(GetAllRequest request = null);
		
		/// <summary>
		/// Returns one CustomerEventDto by Id
		/// </summary>
		[Get("/api/CustomerEvent/{request.Id}")]
		Task<CustomerEventDto> Get(GetCustomerEventRequest request);
		
		/// <summary>
		/// Creates one CustomerEventDto
		/// </summary>
		[Post("/api/CustomerEvent")]
		Task<CustomerEventDto> Create([Body]CreateCustomerEventRequest request);
		
		/// <summary>
		/// Updates one CustomerEventDto by Id
		/// </summary>
		[Put("/api/CustomerEvent/{request.Id}")]
		Task<CustomerEventDto> Update([Body]UpdateCustomerEventRequest request);
		
		/// <summary>
		/// Deletes one CustomerEventDto by Id
		/// </summary>
		[Delete("/api/CustomerEvent/{request.Id}")]
		Task Delete(DeleteCustomerEventRequest request);
	
	}

}
