
//*****************************************************
// <auto-generated>
//   Generated by the cybtans protocol buffer compiler.  DO NOT EDIT!
//   Powered By Cybtans    
// </auto-generated>
//******************************************************

using System.Threading.Tasks;
using mds = global::Cybtans.Tests.Models;

namespace Cybtans.Tests.Clients
{
	public interface IReadOnlyEntityServiceClient
	{
		
		/// <summary>
		/// Returns a collection of ReadOnlyEntityDto
		/// </summary>
		Task<mds::GetAllReadOnlyEntityResponse> GetAll(mds::GetAllRequest request = null);
		
		/// <summary>
		/// Returns one ReadOnlyEntityDto by Id
		/// </summary>
		Task<mds::ReadOnlyEntityDto> Get(mds::GetReadOnlyEntityRequest request);
	
	}

}
